### ISSUE TITLE
Android <5. 'request' returns 'true' instead of 'granted'

### ISSUE THREAD

**Issue by savshen** [moaazsidat/react-native-qrcode-scanner#60]
https://github.com/moaazsidat/react-native-qrcode-scanner/blob/ce18aee444b5c706fbd228b76f62807f30c9518c/index.js#L109

on Android <5 'request' promise resolves to 'true' instead of 'granted': https://facebook.github.io/react-native/docs/permissionsandroid.html

And hence not authorized view is shown always:
![screenshot_1514019880](https://user-images.githubusercontent.com/18660874/34318468-261052a2-e7d1-11e7-97b2-1949668292e3.png)

**Comment by kornji** [comment]
I found this message on Adnroid Version 5.0 too..

**Comment by kornji** [comment]
I try to check data type before assign value. it's work...
![image](https://user-images.githubusercontent.com/3823224/34324562-e3391d72-e8a9-11e7-9153-b7624100f6ee.png)

**Comment by moaazsidat** [comment]
accepting PRs to fix this, thanks!

**Comment by moaazsidat** [comment]
i've pushed a temp fix for this in 0.0.29

**Comment by avencat** [comment]
Hello! @moaazsidat What is the temp fix you pushed please? I have 0.0.29 and still have this error… :( `react-native-camera` in v.1.0.0 manage like this:
```javascript
isAuthorized: Platform.Version >= 23 ? granted === PermissionsAndroid.RESULTS.GRANTED : granted === true;
```
But I found that here, in v.0.0.29, we're still using
```javascript
isAuthorized: granted ===  PermissionsAndroid.RESULTS.GRANTED
```
